# Generated by Django 5.0.7 on 2024-07-19 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('hotel_amount', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
