# Generated by Django 5.0.7 on 2024-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
